apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: "{{ .Values.statefulset.replicas }}"
  serviceName: "mongodb-headless"
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      name: mongodb
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.statefulset.image}}:{{.Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi


